let info = [{
    id: "1",
    titleimg: "images/appliance-repair.png",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "Refrigerator Repair",
    productImage: "                                            images/double-door-fridge.png",
},
{
    id: "2",
    titleimg: "                                            images/makeup-&-styling.png",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "Washing Machine Repair",
    productImage: "                                            images/frontload-washing-machine.png",

},
{
    id: "3",
    titleimg: "                                            images/movers-&-storage.png",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "Air Conditioner Repair",
    productImage: "                                            images/ac.png",
},
{
    id: "4",
    titleimg: "                                            images/handyman-services-(2).jpeg",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "Microwave Repair",
    productImage: "                                            images/microwave.png",
},
{
    id: "5",
    titleimg: "                                            images/painting-&-interior.png",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "Oven Repair",
    productImage: "                                            images/topload-washing-machine.png",
},
{
    id: "6",
    titleimg: "                                            images/handyman-services.jpeg",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "Dishwasher Repair",
    productImage: "                                            images/mixer.png",
},
{
    id: "7",
    titleimg: "                                            images/appliance-repair.png",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "hello-7",
    productImage: "                                            images/mixer.png",
},
{
    id: "6",
    titleimg: "                                            images/handyman-services.jpeg",
    fridgeImg: "                                            images/double-door-fridge.png",
    washingImg: "                                            images/frontload-washing-machine.png",
    microImg: "                                            images/microwave.png",
    mixerImg: "                                            images/mixer.png",
    roImg: "                                            images/ro.png",
    roofFanImg: "                                            images/roof-fan.png",
    geyserImg: "                                            images/geyser.png",
    acImg: "                                            images/ac.png",
    coolerImg: "                                            images/topload-washing-machine.png",
    dishWashImg: "                                            images/ro.png",
    productName: "Dishwasher Repair",
    productImage: "                                            images/mixer.png",
}];
